version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"

  system-api:
    build: ./system-api
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq

  system-worker:
    build: ./system-worker
    depends_on:
      - rabbitmq
      - minio
